debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.http]
        address = ":80"
        compress = true

    [entryPoints.traefik]
        address = ":8080"
        [entryPoints.traefik.auth]
            [entryPoints.traefik.auth.basic]
                usersFile = "/auth/.htpasswd"

[api]
dashboard = true
entrypoint = "traefik"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.local"
exposedByDefault = false
swarmMode = true
watch = true
network = "traefik_proxy"