debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
    compress = true

    [entryPoints.traefik]
    address = ":8080"
    [entryPoints.traefik.auth]
        [entryPoints.traefik.auth.basic]
            users = [
                "admin:$2y$05$cOrY/sgLgdB0l4.A.kyBTuH3tQRz6SGufocTcisEmqfEz9GMO7epu",
            ]

[api]
dashboard = true
entrypoint = "traefik"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
exposedByDefault = false
swarmMode = true
watch = true
network = "proxy"

[file]
  [backends]
    [backends.traefik]
      [backends.traefik.servers.manager0]
      url = "http://192.168.1.10:8080"
      [backends.traefik.servers.manager1]
      url = "http://192.168.1.11:8080"
      [backends.traefik.servers.manager2]
      url = "http://192.168.1.12:8080"