version: '3.7'

services:
  mariadb:
    image: yobasystems/alpine-mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]