version: '3.7'

services:
  agent:
    restart: always
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_SECRET: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    restart: always
    image: portainer/portainer
    environment:
      AGENT_SECRET: portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      - portainer_agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  portainer_agent:
    driver: overlay
    attachable: true

volumes:
  portainer:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.30,rw
      device: ":/media/storage/nfs/data/portainer"