version: '3'

services:
  mongo-srv0:
    hostname: mongo-srv0
    build:
      context: .
      dockerfile: mongo.Dockerfile
    image: mongo-key:latest
    # image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo-root-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-passwd
    networks:
      mongo-net:
        ipv4_address: 172.20.0.20
    ports:
      - 27017:27017
    secrets:
      - mongo-root-username
      - mongo-root-passwd
    command: mongod --auth --bind_ip_all --replSet=rs0 --keyFile /keys/mongo-keyfile

  mongo-srv1:
    hostname: mongo-srv1
    build:
      context: .
      dockerfile: mongo.Dockerfile
    image: mongo-key:latest
    # image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo-root-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-passwd
    networks:
      mongo-net:
        ipv4_address: 172.20.0.21
    ports:
      - 27018:27017
    secrets:
      - mongo-root-username
      - mongo-root-passwd
    command: mongod --auth --bind_ip_all --replSet=rs0 --keyFile /keys/mongo-keyfile

  mongo-srv2:
    hostname: mongo-srv2
    build:
      context: .
      dockerfile: mongo.Dockerfile
    image: mongo-key:latest
    # image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo-root-username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-passwd
    networks:
      mongo-net:
        ipv4_address: 172.20.0.22
    ports:
      - 27019:27017
    secrets:
      - mongo-root-username
      - mongo-root-passwd
    command: mongod --auth --bind_ip_all --replSet=rs0 --keyFile /keys/mongo-keyfile

secrets:
  mongo-root-username:
     file: C:\Users\FlorentinTh\Desktop\DB\secrets/mongo-root-username.txt
  mongo-root-passwd:
     file: C:\Users\FlorentinTh\Desktop\DB\secrets/mongo-root-passwd.txt

networks:
  mongo-net:
    name: mongo-net
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24