version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    environment:
      - TZ=CA/Montreal
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - ../secrets/.certs/:/etc/traefik/certs/
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: proxy-config
        target: /etc/traefik/traefik.toml
        mode: 0440
    secrets:
      - source: traefik-htpasswd
        target: /etc/traefik/.htpasswd
    networks:
      - proxy-net
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=proxy-net
        - traefik.port=8080
        - traefik.backend=traefik
        - traefik.enable=true
        - traefik.frontend=traefik
        - traefik.frontend.rule=PathPrefixStrip:/traefik
        - traefik.frontend.auth.basic.usersFile=/etc/traefik/.htpasswd
        - traefik.frontend.headers.SSLRedirect=true
        - traefik.frontend.entryPoints=http,https
    logging:
      driver: json-file
      options:
        max-size: 50000k
        max-file: 1

configs:
  proxy-config:
    file: ../confs/proxy/conf.toml

secrets:
  traefik-htpasswd:
    file: ../secrets/proxy/.htpasswd
    name: traefik-htpasswd

networks:
  proxy-net:
    driver: overlay
    name: proxy-net
