version: '3.7'

services:
  agent:
    image: portainer/agent:1.3.0
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_SECRET: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /etc/localtime:/etc/localtime
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - agent
    deploy:
      mode: global
      labels:
        - "traefik.enable=false"

  gui:
    image: portainer/portainer:1.21.0
    environment:
      AGENT_SECRET: portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - target: 9000
        published: 9000
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
      - type: volume
        source: data
        target: /data
    networks:
      - agent
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.docker.network=traefik_proxy"
        - "traefik.backend=portainer"
        - "traefik.frontend.rule=PathPrefixStrip:/portainer/"
        - "traefik.port=9000"
        - "traefik.enable=true"

networks:
  agent:
    driver: overlay
    attachable: true
  proxy:
    external: true
    name: traefik_proxy

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.30,rw,nolock
      device: ":/mnt/nfs/data/portainer"