version: '3.7'

services:
  registry:
    restart: always
    container_name: registry
    image: registry:2.7.1
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /mnt/nfs/registry/images:/var/lib/registry
      # - /docker_data/certs:/certs
      - /mnt/nfs/registry/auth:/auth