version: '3.7'

services: 
  proxy:
    image: traefik:1.7.12
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 8080
        published: 8080
        mode: ingress
      - target: 443
        protocol: tcp
        published: 443
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/nfs/auth/traefik/:/auth
      - /etc/localtime:/etc/localtime
    configs:
      - source: traefik
        target: /traefik.toml
    networks:
      - proxy
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.docker.network=traefik_proxy"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=PathPrefixStrip:/traefik"
        - "traefik.port=8080"
        - "traefik.enable=true"

networks:
  proxy:
    driver: overlay

configs:
  traefik: 
    file: /mnt/nfs/conf/traefik.toml